importing the libraries

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn import svm
from sklearn.metrics import accuracy_score

data analysis and collection

In [2]:
diabetes_dataset=pd.read_csv(r"C:\Users\svija\Downloads\diabetes.csv")

In [3]:
diabetes_dataset.head()#pd.read_csv run theese lines and get what are all the parameter used inside this

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [4]:
diabetes_dataset.groupby("Outcome").mean()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
Outcome                                                                      
0           3.298000  109.980000      68.184000      19.664000   68.792000   
1           4.865672  141.257463      70.824627      22.164179  100.335821   

               BMI  DiabetesPedigreeFunction        Age  
Outcome                                                  
0        30.304200                  0.429734  31.190000  
1        35.142537                  0.550500  37.067164

In [5]:
diabetes_dataset.describe()

Pregnancies     Glucose  BloodPressure  SkinThickness     Insulin  \
count   768.000000  768.000000     768.000000     768.000000  768.000000   
mean      3.845052  120.894531      69.105469      20.536458   79.799479   
std       3.369578   31.972618      19.355807      15.952218  115.244002   
min       0.000000    0.000000       0.000000       0.000000    0.000000   
25%       1.000000   99.000000      62.000000       0.000000    0.000000   
50%       3.000000  117.000000      72.000000      23.000000   30.500000   
75%       6.000000  140.250000      80.000000      32.000000  127.250000   
max      17.000000  199.000000     122.000000      99.000000  846.000000   

              BMI  DiabetesPedigreeFunction         Age     Outcome  
count  768.000000                768.000000  768.000000  768.000000  
mean    31.992578                  0.471876   33.240885    0.348958  
std      7.884160                  0.331329   11.760232    0.476951  
min      0.000000                  0.078000   21.000000    0.000000  
25%     27.300000                  0.243750   24.000000    0.000000  
50%     32.000000                  0.372500   29.000000    0.000000  
75%     36.600000                  0.626250   41.000000    1.000000  
max     67.100000                  2.420000   81.000000    1.000000

In [6]:
diabetes_dataset["Outcome"].value_counts()

Outcome
0    500
1    268
Name: count, dtype: int64

In [7]:
diabetes_dataset.shape

(768, 9)

In [8]:
x=diabetes_dataset.drop(columns="Outcome",axis=1)
y=diabetes_dataset["Outcome"]

In [9]:
print(x)

     Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  
0                       0.627   50  
1                       0.351   31  


In [10]:
print(y)

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64


standard the data

In [11]:
scalar=StandardScaler()# we usse standardscaler to arrange the data in particular range in the above data are not in particular range it will complex for predicting machine learninng 


In [12]:
scalar.fit(x)
standard_data=scalar.transform(x)
#or
#standard_data=scalar.fit_transform(x)


In [13]:
standard_data

array([[ 0.63994726,  0.84832379,  0.14964075, ...,  0.20401277,
         0.46849198,  1.4259954 ],
       [-0.84488505, -1.12339636, -0.16054575, ..., -0.68442195,
        -0.36506078, -0.19067191],
       [ 1.23388019,  1.94372388, -0.26394125, ..., -1.10325546,
         0.60439732, -0.10558415],
       ...,
       [ 0.3429808 ,  0.00330087,  0.14964075, ..., -0.73518964,
        -0.68519336, -0.27575966],
       [-0.84488505,  0.1597866 , -0.47073225, ..., -0.24020459,
        -0.37110101,  1.17073215],
       [-0.84488505, -0.8730192 ,  0.04624525, ..., -0.20212881,
        -0.47378505, -0.87137393]])

In [14]:
x=standard_data
y=y

In [15]:
xtrain,xtest,ytrain,ytest=train_test_split(x,y,stratify=y,test_size=0.2,random_state=2)

In [16]:
xtrain

array([[-1.14185152, -0.05929342, -3.57259724, ...,  0.05170968,
        -0.9992857 , -0.78628618],
       [ 0.63994726, -0.49745345,  0.04624525, ..., -0.15136112,
        -1.05666795,  0.31985461],
       [-0.84488505,  2.13150675, -0.47073225, ..., -0.24020459,
        -0.2231152 ,  2.19178518],
       ...,
       [ 2.12477957, -1.12339636,  0.25303625, ..., -0.24020459,
        -0.51908683,  0.14967911],
       [ 0.04601433, -0.27837344,  0.45982725, ...,  0.94014439,
        -0.71237443,  0.40494237],
       [-1.14185152, -1.09209922, -0.05715025, ...,  0.48323511,
        -0.70633419, -0.70119842]])

In [17]:
xtest

array([[-0.25095213, -0.46615631,  0.14964075, ..., -0.78595734,
        -0.79995787, -0.53102292],
       [-0.25095213, -0.24707629, -1.29789624, ..., -1.21748278,
        -1.00230582, -0.95646168],
       [ 0.3429808 ,  0.81702665,  0.45982725, ...,  0.2167047 ,
        -0.76673656,  2.7023117 ],
       ...,
       [-0.54791859, -0.34096773,  0.25303625, ...,  0.05170968,
         0.6829204 , -0.53102292],
       [-0.54791859, -1.24858494,  0.14964075, ..., -0.24020459,
         0.22688248, -0.70119842],
       [ 2.7187125 , -0.46615631,  0.14964075, ...,  0.58477051,
        -0.88754131,  1.00055664]])

In [18]:
ytrain

619    1
329    0
13     1
476    1
45     1
      ..
303    1
592    1
559    0
725    0
253    0
Name: Outcome, Length: 614, dtype: int64

In [19]:
ytest

615    0
80     0
148    0
132    1
501    0
      ..
127    0
185    1
85     0
497    0
86     0
Name: Outcome, Length: 154, dtype: int64

In [20]:
print(x.shape,xtrain.shape,xtest.shape)

(768, 8) (614, 8) (154, 8)


In [21]:
print(y.shape,ytrain.shape,ytest.shape)

(768,) (614,) (154,)


trainig a model


In [22]:
classifier=svm.SVC(kernel="linear")#svc is support vector classifier

In [23]:
classifier.fit(xtrain,ytrain)

SVC(kernel='linear')

model evalutaion how many time model will predict coorectly


In [24]:
xtrain_acc=classifier.predict(xtrain)# due too th small amount data aur accuracy score is good 
trainig_accuracy=accuracy_score(xtrain_acc,ytrain)
print("the accuracy of training data is ",trainig_accuracy)

the accuracy of training data is  0.7866449511400652


In [25]:
xtest_accur=classifier.predict(xtest)
test_accuracy=accuracy_score(xtest_accur,ytest)
print("the accuracy score of test data is :",test_accuracy)# when trianig accuracy is high and test accuracy is low it is called overfitting

the accuracy score of test data is : 0.7727272727272727


In [40]:
inp=[]
input1=int(input("enter the pregnancies:"))
inp.append(input1)
inp2=int(input("enter the gulcose level:"))
inp.append(inp2)
inp3=int(input("enter the blood pressure level:"))
inp.append(inp3)
inp4=int(input("enter the skin thhickness level:"))
inp.append(inp4)
inp5=int(input("enter the insulin level:"))
inp.append(inp5)
inp6=float(input("enter the skin BMI level:"))
inp.append(inp6)
inp7=float(input("enter the diabetes percentage:"))
inp.append(inp7)
inp8=int(input("enter the age :"))
inp.append(inp8)
print(inp)



[12, 50, 50, 20, 348, 0.0, 0.345, 21]


In [42]:
imput_data=tuple(inp)
#changing data into array
imput_data_array=np.asarray(imput_data)
#reshape th data as we are predicting for one instance
input_data_reshape=imput_data_array.reshape(1,-1)
#transform the data
final_data=scalar.transform(input_data_reshape)
print(final_data)

[[ 2.42174604 -2.21879645 -0.98770975 -0.03365099  2.32875721 -4.06047387
  -0.38318149 -1.04154944]]


c:\Users\svija\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(


In [43]:
prediction=classifier.predict(final_data)
print(prediction)

[0]


In [44]:
if prediction[0]==0:
    print("the person is not diabetes")
else:
    print("the person is not diabetes")  

the person is not diabetes
